### ISSUE TITLE
[Wordpress] Support IPv6 only stack on AWS Lightsail

### ISSUE THREAD

**Issue by enapupe** [bitnami/vms#1419] opened 2024-02-20 12:12 UTC
### Describe your suggestion as much as you can

I currently run a wordpress instance under a load balancer on AWS Lightsail, I'd like to have the instance running just on IPv6 to save $ on the unnecessary public IPv4. The base image currently doesn't support the Ipv6 only stack. Is that something you plan addressing anytime soon? THanks!

**Comment by gongomgra** [comment] 2024-02-21 11:09
Hi @enapupe,

Thanks for using Bitnami. I have launched an EC2 instance with IPv6 address and I am able to see the WordPress website using the IPv6 public address without any change in the Apache or WordPress configuration. Which issue are you facing?

![Screenshot 2024-02-21 at 12 09 18](https://github.com/bitnami/vms/assets/6660452/abc5fdef-f088-4757-9333-adb7838f23db)

**Comment by enapupe** [comment] 2024-02-21 11:17
Hello!
I'm unable to create a IPv6 **only** instance on Lightsail. Other base images can, so I assumed this is related to the base image, which I understand is maintained by you.
Thanks again!

<img width="1012" alt="image" src="https://github.com/bitnami/vms/assets/291082/70a00247-1a28-4e50-8166-51b31efd8c04">

**Comment by gongomgra** [comment] 2024-02-26 10:28
Hi @enapupe,

Sorry for the delay. Can you try it in other regions? With regular EC2 instances I had to launch it in a different region (`us-east-2`) because `us-east-1` region didn't support IPv6 instances.

**Comment by enapupe** [comment] 2024-02-29 14:04
By the way, maybe this issue should have been opened in https://github.com/bitnami/containers/ ?

**Comment by gongomgra** [comment] 2024-02-29 15:39
Hi @enapupe,

Can you try to launch an EC2 instance instead of a Lightsail one?

**Comment by gongomgra** [comment] 2024-02-29 15:53
@enapupe There is another question in this forum from a user who seems to have launched an IPv6 instance (not sure if IPv4 + IPv6 though). Can you ask him for further information? Not sure if you need to create anything else in Lightsail panel, but for EC2 instances I had to create my own VPC with IPv6 support and a public IPv6 range of addresses.

https://github.com/bitnami/vms/issues/1423

Hope it helps!

**Comment by enapupe** [comment] 2024-02-29 17:08
Not sure if that issue is related.
My concern is that AWS Lightsail doesn't allow you to create a IPv6 ONLY instance for the Wordpress blueprint by Bitnami, only IPv4+IPv6.

I'm starting to consider picking a base OS blueprint and installing WP myself.

**Comment by gongomgra** [comment] 2024-03-06 16:00
Hi @enapupe,

I have reproduced your issue of not being able to launch a WordPress instance in Lightsail with IPv6 only. We have an internal task to review and fix that, but we have not being able to check it yet. I suggested asking the other user in case he can provide more information on the exact steps he followed or if it is available for some of our assets only. Sorry for the inconveniences.

**Comment by enapupe** [comment] 2024-03-06 16:23
Cool, thanks

I'm still not convinced that other issue has any relation to this.
In any case, I've spinned a regular ec2 instance with bitnami's image
rather than Lightsail, that gave me enough customization to skip the public
ipv4 and life is good.

**Comment by gongomgra** [comment] 2024-03-07 08:38
Hi @enapupe,

Thanks for your message. I'm glad launching a regular EC2 instance worked for you. We will close this ticket as solved. Please do not hesitate to open a new one with any other questions you may have.

**Closed by gongomgra** 2024-03-07 08:38 UTC
Labels: triage, wordpress
