### ISSUE TITLE
[WordPress] bncert-tool update causes an error - lightsail

### ISSUE THREAD

**Issue by dankings001** [bitnami/vms#403] opened 2022-10-17 10:30 UTC
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

43736434-f5ee-2920-d9ca-eeb3987dc1cb

### bndiagnostic output

[Apache]

Found recent Pagespeed related error messages in the Apache error log:
```
[Mon Oct 17 10:05:59.554548 2022] [pagespeed:error] [pid 18133:tid 
139883838162688] [mod_pagespeed **ip_address**-0 @18133] PageSpeed Serf fetch 
failure rate extremely high; only 63 of 250 recent fetches fully successful; is 
fetching working?

```
Press [Enter] to continue:
We suggest disabling pagespeed and check if that improves the behavior. Please 
check the following guide to disable Pagespeed:
 
https://docs.bitnami.com/general/apps/wordpress/administration/use-pagespe
ed/#disable-pagespeed

Found recent error or warning messages in the Apache error log.
```
[Mon Oct 17 10:17:43.760857 2022] [proxy_fcgi:error] [pid 18133:tid 
139884350117632] [client **ip_address**:57470] AH01079: failed to make 
connection to backend: httpd-UDS, referer: 
https://dan-king.co.uk/wp-admin/options-general.php?page=updraftplus
 [Mon Oct 17 10:17:43.782672 2022] [proxy:error] [pid 18133:tid 139884350117632] 
(2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain 
socket /opt/bitnami/php/var/run/www.sock (www-fpm) failed
 [Mon Oct 17 10:17:43.782713 2022] [proxy_fcgi:error] [pid 18133:tid 
139884350117632] [client **ip_address**:57470] AH01079: failed to make 
connection to backend: httpd-UDS, referer: 
https://dan-king.co.uk/wp-admin/options-general.php?page=updraftplus

```
Please check the following guide to troubleshoot server issues:
 
Press [Enter] to continue:
https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/

[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 481 336 9 56 136 76 Swap: 634 
342 292
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Php]

The following error appears in the 
/opt/bitnami/php/var/log/php-fpm.log:
```
[16-Oct-2022 23:59:40] WARNING: [pool www] server reached max_children setting 
(5), consider raising it

### bndiagnostic was not useful. Could you please tell us why?

There is an error with the update of the bncert-tool 

### Describe your issue as much as you can

I updated my bncert tool and then it failed. I've several instances on Lightsail and I tested 2 others, I updated another bncert tool and it failed, in a separate instance, i updated my SSH without updating the tool and it was successful. 

**I updated the tool with the latest version:**

Last login: Wed Oct 12 15:54:45 2022 from 52.94.38.36
bitnami@ip-172-26-3-72:~$ sudo /opt/bitnami/bncert-tool
An updated version is available. Would you like to download it? You would need to run it m
anually later. [Y/n]: y

The tool will exit now. To run the updated version run the following command:

/opt/bitnami/bncert-tool

**I then tried to run the tool:**

/opt/bitnami/bncert-tool

bitnami@ip-172-26-3-72:~$ sudo /opt/bitnami/bncert-tool
Welcome to the Bitnami HTTPS Configuration tool.

Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

**The site where i did not update the tool:**

Last login: Wed Oct 12 15:47:58 2022 from 52.94.38.43
bitnami@ip-172-26-2-0:~$ sudo /opt/bitnami/bncert-tool
An updated version is available. Would you like to download it? You would need to run it m
anually later. [Y/n]: n

**I successfully run the bncert tool**

Welcome to the Bitnami HTTPS Configuration tool.

Domains

Please provide a valid space-separated list of domains for which you wish to
configure your web server.

Domain list []: eblresources.com eblresources.co.uk [www.eblresources.com](http://www.eblresources.com/) [www.eblresources](http://www.eblresources/).
co.uk

A certificate was found at /opt/bitnami/letsencrypt/certificates/eblresources.com.crt
It is registered for a different set of domains: eblresources.com [www.eblresources.com](http://www.eblresources.com/).
Do you want to disable/revoke the existing certificate and create a new one? [y/N]: y

**_There appears to be an issue with the update can you suggest a fix?_**

Thanks

Dan

**Comment by jotamartos** [comment] 2022-10-17 10:57
You can try to manually revoke your certs and generate a new one later 

https://docs.bitnami.com/general/how-to/understand-bncert/#manually-revoking-an-existing-certificate

**Comment by dankings001** [comment] 2022-10-17 11:10
I've revoked it... but now what do i do? Thanks

Last login: Mon Oct 17 11:00:12 2022 from 52.94.38.71
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/ctlscript.sh restart apache
Unmonitored apache
Syntax OK
/opt/bitnami/apache2/scripts/ctl.sh : httpd stopped
Syntax OK
/opt/bitnami/apache2/scripts/ctl.sh : httpd started at port 80
Monitored apache
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencr
ypt --tls --email=dan_kings@icloud.com --domains=dan-king.co.uk www.dan-king.co.uk revoke
No help topic for 'www.dan-king.co.uk'
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencr
ypt --tls --email=dan_kings@icloud.com --domains=dan-king.co.uk revoke
2022/10/17 11:08:52 Trying to revoke certificate for domain dan-king.co.uk
2022/10/17 11:08:52 Certificate was revoked.
2022/10/17 11:08:52 Certificate was archived for domain: dan-king.co.uk

**Comment by dankings001** [comment] 2022-10-17 11:12
The bncert tool still doesn't work:

bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

**Comment by onsterion** [comment] 2022-10-17 14:23
Same problem here....

**Comment by jotamartos** [comment] 2022-10-19 07:18
Hi all, 

Could you please let us know the Bitnami solution you are using and its version? We would like to reproduce the issue to understand the problem. 

In the meantime, you can either follow the alternative approach to generate new certificates 

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

or download a previous version using any of these links

https://downloads.bitnami.com/files/bncert/1.0.2/bncert-1.0.2-linux-x64.run
https://downloads.bitnami.com/files/bncert/1.0.1/bncert-1.0.1-linux-x64.run
https://downloads.bitnami.com/files/bncert/1.0.0/bncert-1.0.0-linux-x64.run
https://downloads.bitnami.com/files/bncert/0.8.0/bncert-0.8.0-linux-x64.run

To replace the binary just run these commands 

```
wget -O bncert-linux-x64.run LINK_TO_THE_VERSION_YOU_WANT_TO_USE
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo /opt/bitnami/bncert-tool
```

Please let us know which version works for you. 

Thanks

**Comment by dankings001** [comment] 2022-10-19 07:40
Hi

I'm using approach B: Self-contained installation.

I tried your solution... and it still doesn't work:

Last login: Tue Oct 18 07:47:13 2022 from 52.94.38.36
bitnami@ip-172-26-1-157:~$ wget -O bncert-linux-x64.run https://downloads.bitnami.com/file
s/bncert/1.0.0/bncert-1.0.0-linux-x64.run
--2022-10-19 07:34:42--  https://downloads.bitnami.com/files/bncert/1.0.0/bncert-1.0.0-lin
ux-x64.run
Resolving downloads.bitnami.com (downloads.bitnami.com)... 108.138.233.97, 108.138.233.10,
 108.138.233.19, ...
Connecting to downloads.bitnami.com (downloads.bitnami.com)|108.138.233.97|:443... connect
ed.
HTTP request sent, awaiting response... 200 OK
Length: 28899305 (28M) [binary/octet-stream]
Saving to: ‘bncert-linux-x64.run’

bncert-linux-x64.run   100%[==========================>]  27.56M  25.3MB/s    in 1.1s    

2022-10-19 07:34:43 (25.3 MB/s) - ‘bncert-linux-x64.run’ saved [28899305/28899305]

bitnami@ip-172-26-1-157:~$ sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
bitnami@ip-172-26-1-157:~$ sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

**Comment by dankings001** [comment] 2022-10-19 07:42
Tried the 0.8.0 too:

bitnami@ip-172-26-1-157:~$ wget -O bncert-linux-x64.run https://downloads.bitnami.com/file
s/bncert/0.8.0/bncert-0.8.0-linux-x64.run
--2022-10-19 07:41:20--  https://downloads.bitnami.com/files/bncert/0.8.0/bncert-0.8.0-lin
ux-x64.run
Resolving downloads.bitnami.com (downloads.bitnami.com)... 108.138.233.10, 108.138.233.19,
 108.138.233.22, ...
Connecting to downloads.bitnami.com (downloads.bitnami.com)|108.138.233.10|:443... connect
ed.
HTTP request sent, awaiting response... 200 OK
Length: 28881898 (28M) [binary/octet-stream]
Saving to: ‘bncert-linux-x64.run’

bncert-linux-x64.run   100%[==========================>]  27.54M  23.6MB/s    in 1.2s    

2022-10-19 07:41:22 (23.6 MB/s) - ‘bncert-linux-x64.run’ saved [28881898/28881898]

bitnami@ip-172-26-1-157:~$ sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
bitnami@ip-172-26-1-157:~$ sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
bitnami@ip-172-26-1-157:~$ sudo /opt/bitnami/bncert-tool
----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

**Comment by dilicfrancis** [comment] 2022-10-20 03:15
Thank you for the links @jotamartos 

Others, this might help.
- After step three, `sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run`
- Skip step 4: `sudo /opt/bitnami/bncert-tool` (because bncert-tool is a symlink, like Desktop shortcut, and may still be pointing to the buggy update instead of your new download)
- Run the downloaded binary directly with `sudo /opt/bitnami/bncert/bncert-linux-x64.run`
- If prompted about updating to the new version by your download, choose no.
- This should launch the familiar program for updating your ssl
- You will be informed that your site already has an existing certificate and whether you want to generate a new one. You can respond with "no". Even though expired, your existing certificate will still be renewed by the tool later in the prompts.

Hope this helps. Cheers.

**Comment by dilicfrancis** [comment] 2022-10-20 03:23
Thank you for the links @jotamartos 

Others, this might help.
- After step three, `sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run`
- Skip step 4: `sudo /opt/bitnami/bncert-tool` (because bncert-tool is a symlink, like Desktop shortcut, and may still be pointing to the buggy update instead of your new download)
- Run the downloaded binary directly with `sudo /opt/bitnami/bncert/bncert-linux-x64.run`
- If prompted about updating to the new version by your download, choose no.
- This should launch the familiar program for updating your ssl
- You will be informed that your site already has an existing certificate and whether you want to generate a new one. You can respond with "no". Even though expired, your existing certificate will still be renewed by the tool later in the prompts.

*I used link: https://downloads.bitnami.com/files/bncert/1.0.0/bncert-1.0.0-linux-x64.run i.e. `wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/1.0.0/bncert-1.0.0-linux-x64.run`

Hope this helps. Cheers.

**Comment by dankings001** [comment] 2022-10-20 11:45
sudo /opt/bitnami/letsencrypt/lego --tls --email="dan_kings@icloud.com" --domains="dan-king.co.uk" --domains="www.dan-king.co.uk" --path="/opt/bitnami/letsencrypt" run

Step 3

sudo mv /opt/bitnami/apache2/conf/server.crt /opt/bitnami/apache2/conf/server.crt.old
sudo mv /opt/bitnami/apache2/conf/server.key /opt/bitnami/apache2/conf/server.key.old
sudo mv /opt/bitnami/apache2/conf/server.csr /opt/bitnami/apache2/conf/server.csr.old
sudo ln -sf /opt/bitnami/letsencrypt/certificates/dan-king.co.uk.key /opt/bitnami/apache2/conf/server.key
sudo ln -sf /opt/bitnami/letsencrypt/certificates/dan-king.co.uk.crt /opt/bitnami/apache2/conf/server.crt
sudo chown root:root /opt/bitnami/apache2/conf/server*
sudo chmod 600 /opt/bitnami/apache2/conf/server*

GET THIS:

bitnami@ip-172-26-1-157:~$ sudo mv /opt/bitnami/apache2/conf/server.crt /opt/bitnami/apach
e2/conf/server.crt.old
bitnami@ip-172-26-1-157:~$ sudo mv /opt/bitnami/apache2/conf/server.key /opt/bitnami/apach
e2/conf/server.key.old
bitnami@ip-172-26-1-157:~$ sudo mv /opt/bitnami/apache2/conf/server.csr /opt/bitnami/apach
e2/conf/server.csr.old
**mv: cannot stat '/opt/bitnami/apache2/conf/server.csr': No such file or directory**
bitnami@ip-172-26-1-157:~$ sudo ln -sf /opt/bitnami/letsencrypt/certificates/dan-king.co.u
k.key /opt/bitnami/apache2/conf/server.key
bitnami@ip-172-26-1-157:~$ sudo ln -sf /opt/bitnami/letsencrypt/certificates/dan-king.co.u
k.crt /opt/bitnami/apache2/conf/server.crt
bitnami@ip-172-26-1-157:~$ sudo chown root:root /opt/bitnami/apache2/conf/server*
bitnami@ip-172-26-1-157:~$ sudo chmod 600 /opt/bitnami/apache2/conf/server*
bitnami@ip-172-26-1-157:~$ 

CHECKED MY FILES AND I DON'T HAVE A FILE:

/opt/bitnami/apache2/conf/server.csr

ONLY server.crt and server.key

**Comment by dankings001** [comment] 2022-10-20 11:53
After step 3 tried: sudo /opt/bitnami/bncert/bncert-linux-x64.run

Going round in circles:

Create a free HTTPS certificate with Let's Encrypt

Please provide a valid e-mail address for which to associate your Let's Encrypt 
certificate.

Domain list: dan-king.co.uk www.dan-king.co.uk

Server name: dan-king.co.uk

E-mail address []: dan_kings@icloud.com

The Let's Encrypt Subscriber Agreement can be found at:

https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

Do you agree to the Let's Encrypt Subscriber Agreement? [Y/n]: y


Warning: Please enter a valid email
Press [Enter] to continue:dan_kings@icloud.com
----------------------------------------------------------------------------
Create a free HTTPS certificate with Let's Encrypt

Please provide a valid e-mail address for which to associate your Let's Encrypt 
certificate.

Domain list: dan-king.co.uk www.dan-king.co.uk

Server name: dan-king.co.uk

E-mail address [dan_kingsÂ@icloud.com]: dan_kings@icloud.com

The Let's Encrypt Subscriber Agreement can be found at:

https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

Do you agree to the Let's Encrypt Subscriber Agreement? [Y/n]: y


Warning: Please enter a valid email
Press [Enter] to continue:dan_kings@icloud.com
----------------------------------------------------------------------------
Create a free HTTPS certificate with Let's Encrypt

Please provide a valid e-mail address for which to associate your Let's Encrypt 
certificate.

Domain list: dan-king.co.uk www.dan-king.co.uk

Server name: dan-king.co.uk

E-mail address [dan_kingsÂ@icloud.com]: 

The Let's Encrypt Subscriber Agreement can be found at:

https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

Do you agree to the Let's Encrypt Subscriber Agreement? [Y/n]: y

**Comment by dankings001** [comment] 2022-10-20 11:57
**Gave it a different email address - worked, produced the certificate but the site still shows as NO CERTIFICATE?** 🤬

Server name: dan-king.co.uk

E-mail address [dan_kingsÂ@icloud.com]: learnclub@icloud.com

The Let's Encrypt Subscriber Agreement can be found at:

https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf

Do you agree to the Let's Encrypt Subscriber Agreement? [Y/n]: y


----------------------------------------------------------------------------
Performing changes to your installation

The Bitnami HTTPS Configuration Tool will perform any necessary actions to your 
Bitnami installation. This may take some time, please be patient.

|

An error occurred renewing certificates with Let's Encrypt:


2022/10/20 11:54:11 No key found for account learnclub@icloud.com. Generating a 
P256 key.
2022/10/20 11:54:11 Saved key to 
/opt/bitnami/letsencrypt/accounts/acme-v02.api.letsencrypt.org/learnclub@icloud.c
om/keys/learnclub@icloud.com.key
2022/10/20 11:54:12 Account learnclub@icloud.com is not registered. Use 'run' to 
register a new account.

Please check our documentation and support forums, we'll be happy to help!

* Bitnami Documentation: https://docs.bitnami.com
* Bitnami Community: https://github.com/bitnami/vms

Press [Enter] to continue:
----------------------------------------------------------------------------
Error

An error occurred when applying configurations.

The web server configuration was left unchanged. There was an error in the new 
configuration, so it was reverted.

Failed steps:
* Running Let's Encrypt: Error renewing certificates

Find more details in the log file:

/tmp/bncert-202210201149.log

If you find any issues, please check Bitnami Support forums at:

https://github.com/bitnami/vms

Press [Enter] to continue:

**Comment by ChristopherKrohn** [comment] 2022-10-20 15:00
I had the same problem.
Reverting to the: https://downloads.bitnami.com/files/bncert/1.0.0/bncert-1.0.0-linux-x64.run version solved the problem.

I'll just not update this going forward.

**Comment by jotamartos** [comment] 2022-10-21 07:47
Hi all,

Thank you for confirming a previous version worked for you. Could you please let us know the Bitnami solution you have and its version? We would like to reproduce the issue.

@dankings001, it seems lego can't generate a valid certificate because the email you used is not registered. Please follow the instructions to revoke your current certificates and generate a new one later.

https://docs.bitnami.com/general/how-to/understand-bncert/#manually-revoking-an-existing-certificate

**Comment by ChristopherKrohn** [comment] 2022-10-21 08:08
Not sure how to check what solution and version I run, but I'm giving this a shot:
Bitnami Wordpress 5.5.1-1, running on AWS

**Comment by jotamartos** [comment] 2022-10-21 12:08
Hi @ChristopherKrohn,

I understand the error you are running into with the new versions is this one, correct? 

```
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:

Warning: Currently only installations using the Apache web server are supported.
Please follow the alternative approach described in this guide:

https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#altern
ative-approach

 Make sure you are entering a proper path, or choose a different directory.
Press [Enter] to continue:
----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]:
```

I downloaded bncert 1.0.0 and everything worked as expected so I'm going to investigate the changes we included recently. 

Thanks

**Comment by jotamartos** [comment] 2022-10-21 15:22
Version 1.0.3 of bncert was just released. It includes the fix to make the tool work again with the old installation layout.

**Comment by dankings001** [comment] 2022-10-24 11:49
How do i run the bncert update? Thanks 🙏

**Comment by jotamartos** [comment] 2022-10-25 07:37
Please run the commands in the documentation to download the latest version 

```
cd /tmp
rm -rf bncert-linux-x64.run
wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run
sudo mkdir /opt/bitnami/bncert
sudo mv bncert-linux-x64.run /opt/bitnami/bncert/
sudo chmod +x /opt/bitnami/bncert/bncert-linux-x64.run
sudo ln -sf /opt/bitnami/bncert/bncert-linux-x64.run /opt/bitnami/bncert-tool
sudo /opt/bitnami/bncert-tool
```

https://docs.bitnami.com/aws/how-to/understand-bncert/

**Comment by brent14** [comment] 2022-10-25 18:27
@jotamartos This worked for me.  I was able to update the SSL certificated with the latest version.

**Closed** 2022-10-26 08:02 UTC
Labels: tech-issues, solved

**Comment by hakxcore** [comment] 2023-03-09 09:02
> sudo /opt/bitnami/bncert-tool

Hi, @jotamartos I have followed your mentioned commands, but I'm getting this error can you suggest me relevant changes?


```  ----------------------------------------------------------------------------
bitnami@ip-172-XX-XX-XX:/tmp$ sudo /opt/bitnami/bncert-tool
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default 
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory [/opt/bitnami]: /opt/bitnami

Warning: The web server configuration check failed. Please fix the configuration 
error: 
/bin/sh: 1: /opt/bitnami/apache/sbin/nginx: not found

**Comment by jotamartos** [comment] 2023-03-09 09:20
This issue was reported in this other ticket 

https://github.com/bitnami/vms/issues/698

As you can see, we tried to reproduce the issue but couldn't do so. Let's continue the conversation in that other thread instead of reopening this one.
