### ISSUE TITLE
PHP WordPress Application 

### ISSUE THREAD

**Issue by srvsable** [bitnami/vms#751] opened 2023-03-08 19:08 UTC
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2da2e7cc-32b7-c61e-2e30-4902f59cb4b2

### bndiagnostic output

    ? Resources: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ? Apache: Found possible issues
    ✓ Php: No issues found
[error_log.zip](https://github.com/bitnami/vms/files/10924192/error_log.zip)

### bndiagnostic was not useful. Could you please tell us why?

Cannot find this error in the dndiagnostic: [Mon Mar 06 13:50:18.611946 2023] [proxy:error] [pid 494800:tid 140082824533760] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/bitnami/php/var/run/www.sock (www-fpm:8000) failed [Mon Mar 06 13:50:18.611979 2023] [proxy_fcgi:error] [pid 494800:tid 140082824533760] [client 103.250.137.54:3428] AH01079: failed to make connection to backend: httpd-UDS, referer: 

### Describe your issue as much as you can

Apache service is stopping automatically. The website is becoming unreachable without warning
[access_log-20230305.gz](https://github.com/bitnami/vms/files/10924198/access_log-20230305.gz)

**Comment by mdhont** [comment] 2023-03-09 16:37
This is a duplicate of https://github.com/bitnami/vms/issues/750. I'm proceeding to close this issue.

**Closed by mdhont** 2023-03-09 16:37 UTC
Labels: tech-issues, triage

**Comment by srvsable** [comment] 2023-03-09 23:22
Please indicate what is the resolution?

**Comment by mdhont** [comment] 2023-03-10 16:33
It seems the machine is running low on resources. I recommend upgrading it to a more powerful one.
