### ISSUE TITLE
[Discourse] Starting application 94% paus and cpu utilization after clean default install

### ISSUE THREAD

**Issue by bj97301** [bitnami/vms#300] opened 2022-09-03 19:15 UTC
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

https://bitnami.com/stack/discourse/cloud/google

### bndiagnostic output
no errors just info

### bndiagnostic was not useful. Could you please tell us why?

no errors in the log

### Describe your issue as much as you can

Steps to repro:
* go to: https://bitnami.com/stack/discourse/cloud/google
* click [Launch in Bitnami Launchpad](https://google.bitnami.com/launch/discourse)
* do the config thing with an SSD but otherwise the default settings:
* click create

expected:
finishes the deploy

actual:
stops at 94% and pegs my cup.  After about 10 minutes it seems to have moved on and claims that it has been deployed.  Cpu is still pegged and my site is unresponsive:
![SCR-20220903-gy0](https://user-images.githubusercontent.com/1450431/188284912-cc767bcb-47be-4206-965e-573bdf348b3a.png)

**Comment by bj97301** [comment] 2022-09-05 17:52
thank you for your help 😊. 

I understand per your answers that you were able to run the bnsupport tool, is that true?

The server was very unresponsive. I wasn't able to get the google cloud server monitoring software on it. 

 Discourse is a big application with high resources requirements, can you tell us how many CPUs and RAM memory are you using? 

default settings. I think 2 cpu cores and 2gb of ram. 

The machine initialization process can also be very resources demanding, that's why the server is under a heavy load even before accessing to it. After a couple of days, are you still finding issues with your machine?

I had to shut down the machine after about half a day. Didn't want to pay for the massive amount of cpu time it was taking.

**Comment by gongomgra** [comment] 2022-09-06 07:49
Hi @bj97301,

Thanks for your message. Unfortunately, I was not able to reproduce your issue using our launchpad for Google Cloud. I launched an image with the default server size (2 CPUs and 4 GB of RAM - e2-medium). Can you verify you launched the same one? I can also SSH connect to the machine and it seems to be quite calm right now

```
$ ssh bitnami@34.MY-IP-ADDRESS.119
Linux bitnami-discourse-f413 5.10.0-17-cloud-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
       ___ _ _                   _
      | _ |_) |_ _ _  __ _ _ __ (_)
      | _ \ |  _| ' \/ _` | '  \| |
      |___/_|\__|_|_|\__,_|_|_|_|_|

  *** Welcome to the Discourse(R) packaged by Bitnami 2.8.8-1         ***
  *** Documentation:  https://docs.bitnami.com/google/apps/discourse/ ***
  ***                 https://docs.bitnami.com/google/                ***
  *** Bitnami Forums: https://github.com/bitnami/vms/                 ***
Last login: Tue Sep  6 07:41:08 2022 from ::REDACTED_IP::
bitnami@bitnami-discourse-f413:~$ uptime
 07:43:29 up 46 min,  1 user,  load average: 0.03, 0.02, 0.00
```

Can you try to launch it again just in case? Notice there is a warning in our launchpad mentioning the minimum required resources.

![Screen Shot 2022-09-06 at 09 46 08](https://user-images.githubusercontent.com/6660452/188576892-038a6dd6-ff48-4323-8f3f-eaee637a23db.png)

**Comment by bj97301** [comment] 2022-09-06 14:02
I'll try again with the larger ram server. I did not notice the warning when I did it.

**Comment by bj97301** [comment] 2022-09-06 15:58
I was able to select this: 
<img width="1440" alt="Screen Shot 2022-09-06 at Tuesday, September 6, 2022 8 46 AM" src="https://user-images.githubusercontent.com/1450431/188681789-d8257785-677d-4664-b422-95f65a31c4fc.png">

I selected a 4gb server and fixed the issue.  You should prevent users from selecting the small servers.

**Comment by bj97301** [comment] 2022-09-06 16:14
could i ask for your advice on this:

<img width="1440" alt="Screen Shot 2022-09-06 at Tuesday, September 6, 2022 9 13 AM" src="https://user-images.githubusercontent.com/1450431/188684981-6edb99fe-edcd-47c3-8296-6811afd4a519.png">

seems as though the server is still referencing the IP even though its from the .org site.

**Comment by bj97301** [comment] 2022-09-06 19:36
where did you hide the `./discourse-setup ` file?

**Comment by gongomgra** [comment] 2022-09-07 08:02
Hi @bj97301,

In the launchpad you shouldn't be able to launch a server not meeting the resource requirements, that's why the warning is there and those machine types are greyed out. However, in the Google console, we can't control this.

Regarding the `discourse-setup` file, I understand you are trying to update the application domain. To do so, you have to use the `configure_app_domain` script as explained in the next guide

https://docs.bitnami.com/google/faq/configuration/configure-custom-domain/

As the original issue with the machine type seems to be fixed, I'm closing this ticket to avoid mixing different topics here. If you have any questions regarding the `configure_app_domain` script, please open a new one.

**Closed by gongomgra** 2022-09-07 08:02 UTC
Labels: tech-issues, triage
